// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTB.Restaurace.Infrastructure.Database;

#nullable disable

namespace UTB.Restaurace.Infrastructure.Migrations
{
    [DbContext(typeof(RestauraceDbContext))]
    [Migration("20241211101128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTB.Restaurace.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageSrc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Meal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            Category = "hlavní jídlo",
                            Description = "Křupavý kuřecí řízek podávaný s jemnou bylinkovou omáčkou a čerstvým salátem.",
                            ImageSrc = "/img/chickenSchnitzel.jpg",
                            Name = "Kuřecí řízek v bylinkové omáčce",
                            Price = 165.0
                        },
                        new
                        {
                            Id = 2,
                            Available = false,
                            Category = "hlavní jídlo",
                            Description = "Šťavnatý flank steak, grilovaný na střední propečení, podávaný s bylinkovým máslem.",
                            ImageSrc = "/img/flankSteak.jpg",
                            Name = "Flank Steak",
                            Price = 250.0
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            Category = "hlavní jídlo",
                            Description = "Tradiční české jídlo s pečeným vepřovým masem, knedlíky a zelím.",
                            ImageSrc = "/img/veproKnedloZelo.jpg",
                            Name = "Vepřové s knedlíkem a zelím",
                            Price = 180.0
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            Category = "hlavní jídlo",
                            Description = "Šťavnatý hovězí burger s čerstvou zeleninou a domácí omáčkou.",
                            ImageSrc = "/img/burger.jpg",
                            Name = "Hovězí Burger",
                            Price = 200.0
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            Category = "hlavní jídlo",
                            Description = "Italská pizza s pikantními plátky pepperoni a sýrem mozzarella.",
                            ImageSrc = "/img/pizza.jpg",
                            Name = "Pepperonni pizza",
                            Price = 220.0
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            Category = "hlavní jídlo",
                            Description = "Oblíbený smažený sýr podávaný s hranolky/kroketami a tatarskou omáčkou.",
                            ImageSrc = "/img/smazenySyr.jpg",
                            Name = "Smažený sýr",
                            Price = 150.0
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            Category = "polévka",
                            Description = "Krémová rajčatová polévka zdobená čerstvou bazalkou a parmazánem.",
                            ImageSrc = "/img/tomatoSoup.jpg",
                            Name = "Rajčatová polévka",
                            Price = 95.0
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            Category = "nápoj",
                            Description = "Osvěžující nealkoholický nápoj s originální recepturou.",
                            ImageSrc = "/img/cocaCola.jpg",
                            Name = "Coca Cola",
                            Price = 35.0
                        },
                        new
                        {
                            Id = 9,
                            Available = true,
                            Category = "nápoj",
                            Description = "Populární nealkoholický nápoj s jedinečnou chutí.",
                            ImageSrc = "/img/pepsi.jpg",
                            Name = "Pepsi",
                            Price = 35.0
                        },
                        new
                        {
                            Id = 10,
                            Available = true,
                            Category = "nápoj",
                            Description = "Klasické české pivo s vyváženou chutí a jemnou hořkostí.",
                            ImageSrc = "/img/staropramen.jpg",
                            Name = "Staropramen",
                            Price = 45.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
